name: Trading Stocks Automation

on:
  schedule:
    # Start job at 9:14 AM IST (03:44 UTC) Monday–Friday
    - cron: "44 3 * * 1-5"
  workflow_dispatch: # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Maven Project Until 11:30 AM IST
        run: |
          # Calculate today's end time (11:30 AM IST) in epoch
          end=$(TZ=Asia/Kolkata date -d "today 11:30" +%s)
          
          while [ $(date +%s) -lt $end ]
          do
            echo "Starting Maven task at $(date)"
            mvn clean test -DsuiteXmlFile=./testng.xml || true
            echo "Task finished at $(date). Restarting immediately..."
          done
